apiVersion: v2
name: rosa-aws-prometheus
description: A Helm chart for Kubernetes

type: application

version: 0.2.0

dependencies:
  - name: grafana-cr
    version: "0.5.1"
    repository: "https://rh-mobb.github.io/helm-charts/"
    # repository: file://../grafana-cr
  - name: alloy
    repository: https://grafana.github.io/helm-charts
    version: "0.12.5"

home: "https://rh-mobb.github.io/helm-charts/"

maintainers:
  - name: rh-mobb
