apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-cr.fullname" . }}-certs
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: {{ include "grafana-cr.fullname" . }}-certs