apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-aws-prometheus
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 5s
      # sigV4Auth: true
      # sigV4Region: {{ .Values.aws.region }}
      # sigV4AuthType: default
      # prometheusType: Prometheus
      # prometheusVersion: 2.44.0
      # cacheLevel: 'High'
    name: aws-prometheus
    type: prometheus
    # type: grafana-amazonprometheus-datasource
    url: 'http://localhost:8005/workspaces/{{ .Values.aws.workspaceId }}'
    # http://aws-prometheus-proxy:8005/workspaces/{{ .Values.aws.workspaceId }}/api/v1/remote_write
  # plugins:
  #   - name: grafana-amazonprometheus-datasource
  #     version: 1.0.1
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-cloudwatch
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    access: proxy
    editable: false
    isDefault: false
    name: cloudwatch
    type: cloudwatch
    jsonData:
      defaultRegion: us-east-2
      authType: default
