---
{{- if .Values.uiPlugin.enabled }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  annotations:
    observability.openshift.io/api-support: GeneralAvailability
  name: logging
spec:
  logging:
    logsLimit: 50
    lokiStack:
      name: logging-loki
    schema: otel
    timeout: 30s
  type: Logging
{{ end }}