subscriptions:
  - name: grafana-operator
    channel: v5
    installPlanApproval: Automatic
    source: community-operators
    sourceNamespace: openshift-marketplace

operatorGroups:
  - name: aro-thanos-af
    targetNamespace: ~
