{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rosa-aws-prometheus.serviceAccountName" . }}
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
{{- if .Values.aws.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-grafana-alloy
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-grafana-alloy
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rosa-aws-prometheus.fullname" . }}-grafana-alloy
subjects:
- kind: ServiceAccount
  name: {{ include "rosa-aws-prometheus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-cluster-monitoring-view
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: {{ include "rosa-aws-prometheus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
