# https://github.com/grafana/loki/blob/main/operator/hack/addon_grafana_gateway_ocp_oauth.yaml
{{ if .Values.clf.audit }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "aro-clf-blob.fullname" . }}-audit
  labels:
    {{- include "aro-clf-blob.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Loki (Audit)
    type: loki
    editable: true
    access: proxy
    url: https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/audit/
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      httpHeaderName2: Authorization
      oauthPassThru: true
      # tlsAuthWithCACert: true
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: audit
      httpHeaderValue2: "Bearer {{ .Values.bearertoken }}"
  {{ end }}
