apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-azure
  namespace: openshift-logging
stringData:
  account_name: "{{ .Values.azure.storageAccount }}"
  account_key: "{{ .Values.azure.storageAccountKey }}"
  container: "{{ .Values.azure.storageContainer }}"
  environment: "AzureGlobal"
---
kind: Secret
apiVersion: v1
metadata:
  name: loki-token
  namespace: {{ .Release.Namespace }}
stringData:
  BEARER_TOKEN: {{ .Values.bearertoken }}
type: Opaque