apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "aro-thanos-af.fullname" . }}-prometheus
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    access: proxy
    editable: false
    isDefault: true
    jsonData:
      timeInterval: 5s
    name: prometheus
    type: prometheus
    url: 'http://thanos-querier.{{ .Release.Namespace }}.svc.cluster.local:9090'
